# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_item', to='users.User')),
                ('user_wishlist', models.ManyToManyField(related_name='wishlist_item', to='users.User')),
            ],
        ),
    ]
