# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_item', to='users.User'),
        ),
    ]
